version: '3'

tasks:
  up:
    desc: Dockerの起動
    cmds:
      - docker compose up -d
  down:
    desc: Dockerの終了
    cmds:
      - docker compose down
  build:
    desc: Docker build
    cmds:
      - docker compose build
  ssh:
    desc: ssh Container
    cmds:
      - docker compose exec api /bin/bash
  downall:
    desc: volumeごと削除
    cmds:
     - docker compose down --rmi all --volumes --remove-orphans
  reload:
    desc: FastAPIをreload
    cmds:
     - docker-compose exec api sh -c "cd /app/app && uvicorn main:app --reload"